import { StyleSheet } from 'react-native';

import { colors, radius, spacing, typography } from '@/theme';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background },
  content: {
    flexGrow: 1,
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.xl,
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
  },
  eyebrow: {
    color: colors.primary,
    fontFamily: typography.bold,
    fontSize: typography.size.small,
    letterSpacing: 2,
    marginTop: spacing.lg,
    marginBottom: spacing.md,
  },
  title: {
    color: colors.text,
    fontFamily: typography.bold,
    fontSize: typography.size.title,
  },
  description: {
    color: colors.muted,
    fontFamily: typography.regular,
    fontSize: typography.size.body,
    lineHeight: 24,
    marginTop: spacing.sm,
  },
  summary: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: spacing.lg,
    padding: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    gap: spacing.lg,
  },
  summaryValue: {
    color: colors.text,
    fontFamily: typography.bold,
    fontSize: 24,
    fontVariant: ['tabular-nums'],
  },
  highlight: { color: colors.primary },
  summaryLabel: {
    color: colors.muted,
    fontFamily: typography.regular,
    fontSize: typography.size.small,
  },
  summaryDivider: {
    width: StyleSheet.hairlineWidth,
    height: 36,
    backgroundColor: colors.secondarySurface,
  },
  searchBox: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
  },
  searchInput: {
    flex: 1,
    color: colors.text,
    fontFamily: typography.regular,
    fontSize: typography.size.body,
  },
  filters: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginVertical: spacing.md,
  },
  filter: {
    minHeight: 40,
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
    borderRadius: 999,
    backgroundColor: colors.surface,
  },
  filterActive: { backgroundColor: colors.primary },
  filterText: {
    color: colors.muted,
    fontFamily: typography.semibold,
    fontSize: typography.size.small,
  },
  filterTextActive: { color: colors.onPrimary },
  sectionLabel: {
    color: colors.muted,
    fontFamily: typography.semibold,
    fontSize: typography.size.small,
    marginTop: spacing.sm,
    marginBottom: spacing.xs,
  },
  state: {
    flex: 1,
    minHeight: 280,
    justifyContent: 'center',
    alignItems: 'center',
    gap: spacing.md,
    padding: spacing.lg,
  },
  footer: { marginVertical: spacing.lg },
  stateTitle: {
    color: colors.text,
    fontFamily: typography.bold,
    fontSize: 21,
    textAlign: 'center',
  },
  stateText: {
    color: colors.muted,
    fontFamily: typography.regular,
    fontSize: typography.size.body,
    lineHeight: 24,
    textAlign: 'center',
  },
  retry: {
    minHeight: 48,
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
    borderRadius: radius.md,
    backgroundColor: colors.primary,
  },
  retryText: {
    color: colors.onPrimary,
    fontFamily: typography.bold,
    fontSize: typography.size.body,
  },
});
