import { StyleSheet } from 'react-native';

import { colors, radius, spacing, typography } from '@/theme';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background },
  content: {
    flexGrow: 1,
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.xl,
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: spacing.md,
    padding: spacing.lg,
  },
  topBar: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  iconButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  manageButton: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
  },
  manageText: {
    color: colors.text,
    fontFamily: typography.semibold,
    fontSize: typography.size.small,
  },
  eyebrow: {
    color: colors.primary,
    fontFamily: typography.bold,
    fontSize: typography.size.small,
    letterSpacing: 2,
    marginTop: spacing.md,
    marginBottom: spacing.sm,
  },
  groupTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  groupIcon: {
    width: 52,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
    backgroundColor: colors.surface,
  },
  title: {
    flex: 1,
    color: colors.text,
    fontFamily: typography.bold,
    fontSize: typography.size.title,
  },
  description: {
    color: colors.muted,
    fontFamily: typography.regular,
    fontSize: typography.size.body,
    lineHeight: 24,
    marginTop: spacing.sm,
  },
  rankingTabs: { gap: spacing.sm, paddingVertical: spacing.lg },
  rankingTab: {
    minHeight: 42,
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
  },
  rankingTabActive: { backgroundColor: colors.primary },
  rankingTabText: {
    color: colors.muted,
    fontFamily: typography.semibold,
    fontSize: typography.size.small,
  },
  rankingTabTextActive: { color: colors.onPrimary },
  rankingDescription: {
    color: colors.muted,
    fontFamily: typography.regular,
    fontSize: typography.size.small,
    marginTop: -spacing.sm,
  },
  podium: {
    minHeight: 205,
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  podiumCard: {
    flex: 1,
    minWidth: 0,
    height: 164,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    padding: spacing.sm,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
  },
  firstCard: { height: 190, borderWidth: 1, borderColor: colors.primary },
  medal: {
    minWidth: 34,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: colors.secondarySurface,
  },
  firstMedal: { backgroundColor: colors.primary },
  medalText: { color: colors.text, fontFamily: typography.bold, fontSize: 12 },
  podiumName: {
    width: '100%',
    color: colors.text,
    fontFamily: typography.semibold,
    fontSize: 12,
    textAlign: 'center',
  },
  podiumRating: {
    color: colors.primary,
    fontFamily: typography.bold,
    fontSize: 18,
  },
  podiumMetric: {
    color: colors.muted,
    fontFamily: typography.bold,
    fontSize: 9,
    letterSpacing: 1,
  },
  rankingState: {
    minHeight: 150,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    marginTop: spacing.lg,
    padding: spacing.lg,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
  },
  sectionRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    marginTop: spacing.xl,
    marginBottom: spacing.sm,
  },
  sectionTitle: {
    color: colors.text,
    fontFamily: typography.bold,
    fontSize: 20,
  },
  metricHint: {
    color: colors.muted,
    fontFamily: typography.regular,
    fontSize: typography.size.small,
  },
  rankRow: {
    minHeight: 76,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.secondarySurface,
  },
  position: {
    width: 25,
    color: colors.muted,
    fontFamily: typography.bold,
    fontSize: 16,
    textAlign: 'center',
  },
  topPosition: { color: colors.primary },
  avatarFallback: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
    backgroundColor: colors.surface,
  },
  personText: { flex: 1, minWidth: 0 },
  personName: {
    color: colors.text,
    fontFamily: typography.semibold,
    fontSize: typography.size.body,
  },
  personDetail: {
    color: colors.muted,
    fontFamily: typography.regular,
    fontSize: 12,
    marginTop: 3,
  },
  rating: { alignItems: 'flex-end' },
  ratingValue: {
    color: colors.text,
    fontFamily: typography.bold,
    fontSize: 17,
  },
  ratingLabel: {
    color: colors.muted,
    fontFamily: typography.bold,
    fontSize: 9,
    letterSpacing: 1,
  },
  futureCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    marginTop: spacing.xl,
    padding: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
  },
  futureTitle: {
    color: colors.text,
    fontFamily: typography.bold,
    fontSize: typography.size.body,
  },
  stateTitle: {
    color: colors.text,
    fontFamily: typography.bold,
    fontSize: 21,
    textAlign: 'center',
  },
  stateText: {
    color: colors.muted,
    fontFamily: typography.regular,
    fontSize: typography.size.body,
    lineHeight: 22,
    textAlign: 'center',
  },
  secondaryButton: {
    minHeight: 46,
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
  },
  secondaryText: { color: colors.text, fontFamily: typography.bold },
});
