import { StyleSheet } from 'react-native';

import { colors, radius, spacing, typography } from '@/theme';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background },
  content: {
    flexGrow: 1,
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.xl,
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: spacing.md,
    padding: spacing.lg,
  },
  topBar: {
    minHeight: 64,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  title: {
    flex: 1,
    color: colors.text,
    fontFamily: typography.bold,
    fontSize: 23,
  },
  iconButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notice: {
    flexDirection: 'row',
    gap: spacing.sm,
    padding: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.secondarySurface,
  },
  noticeText: {
    flex: 1,
    color: colors.muted,
    fontFamily: typography.regular,
    lineHeight: 20,
  },
  sectionTitle: {
    color: colors.text,
    fontFamily: typography.bold,
    fontSize: 19,
    marginTop: spacing.xl,
    marginBottom: spacing.sm,
  },
  fieldLabel: {
    color: colors.text,
    fontFamily: typography.semibold,
    fontSize: typography.size.small,
    marginBottom: spacing.sm,
  },
  input: {
    minHeight: 52,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.secondarySurface,
    color: colors.text,
    fontFamily: typography.regular,
    fontSize: typography.size.body,
  },
  counter: {
    color: colors.muted,
    fontFamily: typography.regular,
    fontSize: 11,
    textAlign: 'right',
    marginTop: 4,
    marginBottom: spacing.md,
  },
  saveButton: {
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.primary,
  },
  saveText: { color: colors.onPrimary, fontFamily: typography.bold },
  personRow: {
    minHeight: 70,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.secondarySurface,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
  },
  avatarFallback: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
    backgroundColor: colors.surface,
  },
  personText: { flex: 1 },
  personName: {
    color: colors.text,
    fontFamily: typography.semibold,
    fontSize: typography.size.body,
  },
  personDetail: {
    color: colors.muted,
    fontFamily: typography.regular,
    fontSize: typography.size.small,
    marginTop: 3,
  },
  addButton: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderRadius: radius.md,
    backgroundColor: colors.primary,
  },
  addText: {
    color: colors.onPrimary,
    fontFamily: typography.bold,
    fontSize: 12,
  },
  footer: { paddingBottom: spacing.xl },
  deleteButton: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    marginTop: spacing.xl,
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: radius.md,
  },
  deleteText: { color: colors.primary, fontFamily: typography.bold },
  disabled: { opacity: 0.45 },
  inlineState: {
    alignItems: 'center',
    gap: spacing.md,
    paddingVertical: spacing.md,
  },
  retryButton: {
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
    borderRadius: radius.md,
    backgroundColor: colors.secondarySurface,
  },
  retryText: { color: colors.text, fontFamily: typography.bold },
  stateText: {
    color: colors.muted,
    fontFamily: typography.regular,
    fontSize: typography.size.body,
    lineHeight: 22,
    textAlign: 'center',
  },
  error: {
    color: colors.primary,
    fontFamily: typography.regular,
    marginTop: spacing.md,
  },
});
