import { StyleSheet } from 'react-native';

import { colors, radius, spacing, typography } from '@/theme';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background },
  content: {
    flexGrow: 1,
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.xl,
  },
  header: { marginBottom: spacing.md },
  eyebrow: {
    color: colors.primary,
    fontFamily: typography.bold,
    fontSize: typography.size.small,
    letterSpacing: 2,
    marginTop: spacing.lg,
    marginBottom: spacing.md,
  },
  titleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: spacing.md,
  },
  title: {
    color: colors.text,
    fontFamily: typography.bold,
    fontSize: typography.size.title,
  },
  description: {
    color: colors.muted,
    fontFamily: typography.regular,
    fontSize: typography.size.body,
    lineHeight: 24,
    marginTop: spacing.sm,
  },
  createButton: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.primary,
  },
  createText: {
    color: colors.onPrimary,
    fontFamily: typography.bold,
    fontSize: typography.size.small,
  },
  card: {
    minHeight: 82,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    marginTop: spacing.sm,
    padding: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
  },
  pressed: { opacity: 0.72 },
  cardIcon: {
    width: 46,
    height: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
    backgroundColor: colors.secondarySurface,
  },
  cardText: { flex: 1, gap: 4 },
  cardTitle: {
    color: colors.text,
    fontFamily: typography.bold,
    fontSize: typography.size.body,
  },
  cardDetail: {
    color: colors.muted,
    fontFamily: typography.regular,
    fontSize: typography.size.small,
  },
  state: {
    minHeight: 300,
    justifyContent: 'center',
    alignItems: 'center',
    gap: spacing.md,
    padding: spacing.lg,
  },
  stateTitle: {
    color: colors.text,
    fontFamily: typography.bold,
    fontSize: 21,
    textAlign: 'center',
  },
  stateText: {
    color: colors.muted,
    fontFamily: typography.regular,
    fontSize: typography.size.body,
    textAlign: 'center',
  },
  overlay: {
    flex: 1,
    justifyContent: 'center',
    padding: spacing.lg,
    backgroundColor: 'rgba(0,0,0,0.72)',
  },
  modal: {
    width: '100%',
    maxWidth: 480,
    alignSelf: 'center',
    gap: spacing.md,
    padding: spacing.lg,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modalTitle: { color: colors.text, fontFamily: typography.bold, fontSize: 24 },
  label: {
    color: colors.text,
    fontFamily: typography.semibold,
    fontSize: typography.size.small,
  },
  input: {
    minHeight: 52,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.secondarySurface,
    color: colors.text,
    fontFamily: typography.regular,
    fontSize: typography.size.body,
  },
  counter: {
    color: colors.muted,
    fontFamily: typography.regular,
    fontSize: 11,
    textAlign: 'right',
    marginTop: -spacing.sm,
  },
  error: {
    color: colors.primary,
    fontFamily: typography.regular,
    fontSize: typography.size.small,
  },
  submit: {
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
    backgroundColor: colors.primary,
  },
  disabled: { opacity: 0.45 },
  submitText: {
    color: colors.onPrimary,
    fontFamily: typography.bold,
    fontSize: typography.size.body,
  },
});
